### ISSUE TITLE
AllegatiType missing

### ISSUE THREAD

**Issue by y994379** [Tudor44/fattura-elettronica#2]
hello, where can I find class
it.noriepa.fatturapa.jaxb.AllegatiType

and all package it.noriepa.fatturapa.jaxb

?
thank you

**Comment by gdorsi44** [comment]
Hello @y994379 ,

you have to generate the package maven, during the set up of project (as indicated into readme.md).
Launch the command:

`mvn install` 
or
`mvn generate-sources` 

Warm Regards,
Gaetano.
